---
title: "HW3"
author: "Dakyung Lee"
date: "2024-07-22"
jupyter: python3
---
## 204p

### Q1.  `mpg` 데이터의 `cty(도시 연비)`와 `hwy(고속도로 연비)` 간에 어떤 관게가 있는지 알아보려고 합니다. x축은 `cty`, y축은 `hwy`로 된 산점도를 만들어 보세요.
```{python}
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

mpg = pd.read_csv('../data/mpg.csv')
sns.scatterplot(data = mpg, x = 'cty', y = 'hwy', hue = 'cty')
```

### Q2. 미국의 지역별 인구통계 정보를 담은 `midwest.csv`를 이용해 전체 인구와 아시아인 인구 간에 어떤 관계가 있는지 알아보려고 합니다. x축은 `poptotal(전체 인구)`, y축은 `popasian(아시아인 인구)`으로 된 산점도를 만들어 보세요. 전체 인구는 50만 명 이하, 아시아인 인구는 1만 명 이하인 지역만 산점도에 표시되게 설정하세요.
```{python}

midwest = pd.read_csv('../data/midwest.csv')
sns.scatterplot(data = midwest, x = 'poptotal', y = 'popasian', hue = 'poptotal') \
   .set(xlim = [0, 500000], ylim = [0, 10000])
```

## 211p

### Q1.  어떤 회사에서 생산한 `'suv'`차종의 도시 연비가 높은지 알아보려고 합니다. `'suv'`차종을 대상으로 `cty(도시 연비)` 평균이 가장 높은 회사 다섯 곳을 막대 그래프로 표현해 보세요. 막대는 연비가 높은 순으로 정렬하세요.
```{python}
mpg = pd.read_csv('../data/mpg.csv')

df_mpg = mpg.query('category == "suv"') \
            .groupby('model', as_index = False) \
            .agg(suv_cty_mean = ('cty', 'mean')) \
            .sort_values('suv_cty_mean', ascending = False)[0:5]
            
sns.barplot(data = df_mpg, x = 'model', y = 'suv_cty_mean', hue = 'model')
```

### Q2.  자동차 중에 어떤 `category(자동차 종류)`가 많은지 알아보려고 합니다. `sns.barplot()`을 이용해 자동차 종류별 빈도를 표현한 막대 그래프를 만들어 보세요. 막대는 빈도가 높은 순으로 정렬하세요.
```{python}
df_mpg2 = mpg.groupby('category', as_index = False) \
             .agg(category_count = ('category', 'count')) \
             .sort_values('category_count', ascending = False)
            
sns.barplot(data = df_mpg2, x = 'category', y = 'category_count', hue = 'category')
```

# 교재 08장. 그래프 그리기
## 산점도

* x축은 `displ`, y축은 `hwy`를 나타낸 산점도 만들기
```{python}
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

mpg = pd.read_csv('../data/mpg.csv')

sns.scatterplot(data = mpg, x = 'displ', y = 'hwy')
plt.show()
plt.clf()
```

* x축 범위를 3~6, y축 범위를 10~30으로 제한해 산점도 업데이트
```{python}
sns.scatterplot(data = mpg, x = 'displ', y = 'hwy') \
   .set(xlim = [3, 6], ylim = [10, 30])
plt.show()
plt.clf()
```

* `drv`별로 표식 색깔 다르게 표현
```{python}
sns.scatterplot(data = mpg, x = 'displ', y = 'hwy', hue = 'drv')
plt.show()
plt.clf()
```
 
## 막대 그래프

* 집단별 평균표를 만들고, 막대 그래프 만들기
```{python}
df_mpg = mpg.groupby('drv', as_index = False) \
   .agg(mean_hwy = ('hwy', 'mean'))
df_mpg

sns.barplot(data = df_mpg, x = 'drv', y = 'mean_hwy', hue = 'drv')
plt.show()
plt.clf()

```

* 크기 순으로 정렬하여 막대 그래프 업데이트
```{python}
df_mpg = df_mpg.sort_values('mean_hwy', ascending = False)
sns.barplot(data = df_mpg, x = 'drv', y = 'mean_hwy', hue = 'drv')
plt.show()
plt.clf()
```

* 집단별 빈도표를 만들고, 막대 그래프 만들기
```{python}
df_mpg = mpg.groupby('drv', as_index = False) \
            .agg(n = ('drv', 'count'))
sns.barplot(data = df_mpg, x = 'drv', y = 'n', hue = 'drv')
plt.show()
plt.clf()
```

* `.countplot()`으로 빈도 막대 그래프 만들기
    - `.barplot()`과의 차이: `countplot()`은 별도로 빈도표를 만드는 작업이 필요하지 않다.
```{python}
sns.countplot(data = mpg, x = 'drv', hue = 'drv')
plt.show()
plt.clf()
```


# Plotly를 활용한 인터랙티브 그래프 그리기
## Plotly 산점도

* 산점도 만들기
```{python}
import plotly.express as px
px.scatter(data_frame = mpg, x = 'cty', y = 'hwy', color = 'drv')
```

## Plotly 막대 그래프

** 자동차 종류별 빈도를 구하고, 막대 그래프 만들기
```{python}
df = mpg.groupby('category', as_index = False) \
        .agg(n = ('category', 'count'))

px.bar(data_frame = df, x = 'category', y = 'n', color = 'category')
```